services:

  pulse:
    image: rcourtman/pulse:latest
    container_name: pulse
    restart: unless-stopped
    ports:
      - "7655:7655"
    environment:
      - PULSE_AUTH_USER=admin
      - PULSE_AUTH_PASS=p4ssw0rd
      - API_TOKEN=abce112be18e8612c10799dbf2d38ae9c649f1759b86252a5d1f1c7a58bd6be6
      - TZ=Europe/Madrid
    volumes:
      - ./pulse_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
